/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.ingsistemas.poo.finanzas.gui;

import com.jtattoo.plaf.noire.NoireLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Administrator
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem36 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBanco = new javax.swing.JMenu();
        itemIniciarSesiónBanco = new javax.swing.JMenuItem();
        itemRegistrarBanco = new javax.swing.JMenuItem();
        itemModificarBanco = new javax.swing.JMenuItem();
        itemEliminarBanco = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuC_Organizacion = new javax.swing.JMenu();
        itemIniciarSesiónC_Org = new javax.swing.JMenuItem();
        itemRegistrarC_Org = new javax.swing.JMenuItem();
        itemListarC_Org = new javax.swing.JMenuItem();
        itemModificarC_Org = new javax.swing.JMenuItem();
        itemEliminarC_org = new javax.swing.JMenuItem();
        menuC_PersonasReales = new javax.swing.JMenu();
        itemIniciarSesiónC_PR = new javax.swing.JMenuItem();
        itemRegistrarC_PR = new javax.swing.JMenuItem();
        itemListarC_PR = new javax.swing.JMenuItem();
        itemModificarC_PR = new javax.swing.JMenuItem();
        itemEliminarC_PR = new javax.swing.JMenuItem();
        ReportesClientesPersona = new javax.swing.JMenu();
        itemRAlfabeticoC_PR = new javax.swing.JMenuItem();
        itemRGeneroC_PR = new javax.swing.JMenuItem();
        menuCuentaAhorro = new javax.swing.JMenu();
        itemCrearCuentaA = new javax.swing.JMenuItem();
        itemListarCuentaA = new javax.swing.JMenuItem();
        itemModificarCuenteA = new javax.swing.JMenuItem();
        itemEliminarCuentaA = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        reportesCuentaAhorro = new javax.swing.JMenu();
        menuCuentaCorriente = new javax.swing.JMenu();
        itemCuentaARegistrar = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        reportesCuentaCorriente = new javax.swing.JMenu();
        menuEmpleado = new javax.swing.JMenu();
        itemEmpleadoRegistrar = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        ReportesEmpleados = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        menuRepresentante = new javax.swing.JMenu();
        itemRepresentanteRegistrar = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        menuSucursal = new javax.swing.JMenu();
        itemSucursalRegistrar = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        reportesSucursal = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        jMenuItem36.setText("jMenuItem36");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/fondos/Oceano.jpg"))); // NOI18N

        menuBanco.setText("Banco");

        itemIniciarSesiónBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/log 24px.png"))); // NOI18N
        itemIniciarSesiónBanco.setText("Iniciar sesión");
        menuBanco.add(itemIniciarSesiónBanco);

        itemRegistrarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemRegistrarBanco.setText("Registrar");
        itemRegistrarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarBancoActionPerformed(evt);
            }
        });
        menuBanco.add(itemRegistrarBanco);

        itemModificarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        itemModificarBanco.setText("Modificar");
        menuBanco.add(itemModificarBanco);

        itemEliminarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        itemEliminarBanco.setText("Eliminar");
        menuBanco.add(itemEliminarBanco);
        menuBanco.add(jSeparator1);

        jMenuBar1.add(menuBanco);

        menuC_Organizacion.setText("C_Organizacion");

        itemIniciarSesiónC_Org.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/log 24px.png"))); // NOI18N
        itemIniciarSesiónC_Org.setText("Iniciar sesión");
        menuC_Organizacion.add(itemIniciarSesiónC_Org);

        itemRegistrarC_Org.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemRegistrarC_Org.setText("Registrar");
        itemRegistrarC_Org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarC_OrgActionPerformed(evt);
            }
        });
        menuC_Organizacion.add(itemRegistrarC_Org);

        itemListarC_Org.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        itemListarC_Org.setText("Listar");
        menuC_Organizacion.add(itemListarC_Org);

        itemModificarC_Org.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        itemModificarC_Org.setText("Modificar");
        menuC_Organizacion.add(itemModificarC_Org);

        itemEliminarC_org.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        itemEliminarC_org.setText("Eliminar");
        menuC_Organizacion.add(itemEliminarC_org);

        jMenuBar1.add(menuC_Organizacion);

        menuC_PersonasReales.setText("C_PersonasReales");

        itemIniciarSesiónC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/log 24px.png"))); // NOI18N
        itemIniciarSesiónC_PR.setText("Iniciar sesión");
        menuC_PersonasReales.add(itemIniciarSesiónC_PR);

        itemRegistrarC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemRegistrarC_PR.setText("Registrar");
        itemRegistrarC_PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarC_PRActionPerformed(evt);
            }
        });
        menuC_PersonasReales.add(itemRegistrarC_PR);

        itemListarC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        itemListarC_PR.setText("Listar");
        menuC_PersonasReales.add(itemListarC_PR);

        itemModificarC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        itemModificarC_PR.setText("Modificar");
        itemModificarC_PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarC_PRActionPerformed(evt);
            }
        });
        menuC_PersonasReales.add(itemModificarC_PR);

        itemEliminarC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        itemEliminarC_PR.setText("Eliminar");
        menuC_PersonasReales.add(itemEliminarC_PR);

        ReportesClientesPersona.setText("Reportes");

        itemRAlfabeticoC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/all.png"))); // NOI18N
        itemRAlfabeticoC_PR.setText("Todos");
        ReportesClientesPersona.add(itemRAlfabeticoC_PR);

        itemRGeneroC_PR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/gender.png"))); // NOI18N
        itemRGeneroC_PR.setText("Genero");
        itemRGeneroC_PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRGeneroC_PRActionPerformed(evt);
            }
        });
        ReportesClientesPersona.add(itemRGeneroC_PR);

        menuC_PersonasReales.add(ReportesClientesPersona);

        jMenuBar1.add(menuC_PersonasReales);

        menuCuentaAhorro.setText("CuentaAhorro");

        itemCrearCuentaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemCrearCuentaA.setText("Crear");
        itemCrearCuentaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCuentaAActionPerformed(evt);
            }
        });
        menuCuentaAhorro.add(itemCrearCuentaA);

        itemListarCuentaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        itemListarCuentaA.setText("Listar");
        itemListarCuentaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCuentaAActionPerformed(evt);
            }
        });
        menuCuentaAhorro.add(itemListarCuentaA);

        itemModificarCuenteA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        itemModificarCuenteA.setText("Modificar");
        menuCuentaAhorro.add(itemModificarCuenteA);

        itemEliminarCuentaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        itemEliminarCuentaA.setText("Eliminar");
        menuCuentaAhorro.add(itemEliminarCuentaA);
        menuCuentaAhorro.add(jSeparator2);

        reportesCuentaAhorro.setText("Reportes");
        menuCuentaAhorro.add(reportesCuentaAhorro);

        jMenuBar1.add(menuCuentaAhorro);

        menuCuentaCorriente.setText("CuentaCorriente");
        menuCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentaCorrienteActionPerformed(evt);
            }
        });

        itemCuentaARegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemCuentaARegistrar.setText("Registrar");
        itemCuentaARegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCuentaARegistrarActionPerformed(evt);
            }
        });
        menuCuentaCorriente.add(itemCuentaARegistrar);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        jMenuItem25.setText("Listar");
        menuCuentaCorriente.add(jMenuItem25);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        jMenuItem26.setText("Modificar");
        menuCuentaCorriente.add(jMenuItem26);

        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        jMenuItem27.setText("Eliminar");
        menuCuentaCorriente.add(jMenuItem27);

        reportesCuentaCorriente.setText("Reportes");
        menuCuentaCorriente.add(reportesCuentaCorriente);

        jMenuBar1.add(menuCuentaCorriente);

        menuEmpleado.setText("Empleado");

        itemEmpleadoRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemEmpleadoRegistrar.setText("Registrar");
        itemEmpleadoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoRegistrarActionPerformed(evt);
            }
        });
        menuEmpleado.add(itemEmpleadoRegistrar);

        jMenuItem33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        jMenuItem33.setText("Listar");
        menuEmpleado.add(jMenuItem33);

        jMenuItem34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        jMenuItem34.setText("Modificar");
        menuEmpleado.add(jMenuItem34);

        jMenuItem35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        jMenuItem35.setText("Eliminar");
        menuEmpleado.add(jMenuItem35);

        ReportesEmpleados.setText("Reportes");

        jMenuItem48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/all.png"))); // NOI18N
        jMenuItem48.setText("Todos");
        ReportesEmpleados.add(jMenuItem48);

        jMenuItem49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/gender.png"))); // NOI18N
        jMenuItem49.setText("Genero");
        jMenuItem49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49ActionPerformed(evt);
            }
        });
        ReportesEmpleados.add(jMenuItem49);

        menuEmpleado.add(ReportesEmpleados);

        jMenuBar1.add(menuEmpleado);

        menuRepresentante.setText("Representante");

        itemRepresentanteRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemRepresentanteRegistrar.setText("Registrar");
        itemRepresentanteRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRepresentanteRegistrarActionPerformed(evt);
            }
        });
        menuRepresentante.add(itemRepresentanteRegistrar);

        jMenuItem38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        jMenuItem38.setText("Listar");
        menuRepresentante.add(jMenuItem38);

        jMenuItem39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        jMenuItem39.setText("Modificar");
        menuRepresentante.add(jMenuItem39);

        jMenuItem40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        jMenuItem40.setText("Eliminar");
        menuRepresentante.add(jMenuItem40);

        jMenuBar1.add(menuRepresentante);

        menuSucursal.setText("Sucursal");

        itemSucursalRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add.png"))); // NOI18N
        itemSucursalRegistrar.setText("Registrar");
        itemSucursalRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSucursalRegistrarActionPerformed(evt);
            }
        });
        menuSucursal.add(itemSucursalRegistrar);

        jMenuItem42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/list.png"))); // NOI18N
        jMenuItem42.setText("Listar");
        menuSucursal.add(jMenuItem42);

        jMenuItem43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/modify.png"))); // NOI18N
        jMenuItem43.setText("Modificar");
        menuSucursal.add(jMenuItem43);

        jMenuItem44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete.png"))); // NOI18N
        jMenuItem44.setText("Eliminar");
        menuSucursal.add(jMenuItem44);

        reportesSucursal.setText("Reportes");
        menuSucursal.add(reportesSucursal);

        jMenuBar1.add(menuSucursal);

        menuAyuda.setText("Ayuda");
        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemModificarC_PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarC_PRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemModificarC_PRActionPerformed

    private void itemListarCuentaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCuentaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarCuentaAActionPerformed

    private void itemRegistrarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarBancoActionPerformed
       VentanaGBanco vb= new VentanaGBanco(this, true);
        vb.setLocationRelativeTo(this);
        vb.setVisible(true);
    }//GEN-LAST:event_itemRegistrarBancoActionPerformed

    private void itemRGeneroC_PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRGeneroC_PRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRGeneroC_PRActionPerformed

    private void jMenuItem49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem49ActionPerformed

    private void itemRegistrarC_OrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarC_OrgActionPerformed
        VentanaGC_Organizacion vo= new VentanaGC_Organizacion(this, true);
        vo.setLocationRelativeTo(this);
        vo.setVisible(true);
    }//GEN-LAST:event_itemRegistrarC_OrgActionPerformed

    private void itemRegistrarC_PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarC_PRActionPerformed
        VentanaGC_PR vp= new VentanaGC_PR(this, true);
        vp.setLocationRelativeTo(this);
        vp.setVisible(true);
    }//GEN-LAST:event_itemRegistrarC_PRActionPerformed

    private void itemCrearCuentaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCuentaAActionPerformed
        VentanaGCAhorro vca= new VentanaGCAhorro(this, true);
        vca.setLocationRelativeTo(this);
        vca.setVisible(true);
    }//GEN-LAST:event_itemCrearCuentaAActionPerformed

    private void itemCuentaARegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCuentaARegistrarActionPerformed
        VentanaGCCorriente v = new VentanaGCCorriente(this, true);
        v.setLocationRelativeTo(null);
        v.setVisible(true);
    }//GEN-LAST:event_itemCuentaARegistrarActionPerformed

    private void menuCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentaCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCuentaCorrienteActionPerformed

    private void itemEmpleadoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoRegistrarActionPerformed
        VentanaGEmpleado v = new VentanaGEmpleado(this, true);
        v.setLocationRelativeTo(null);
        v.setVisible(true);        
    }//GEN-LAST:event_itemEmpleadoRegistrarActionPerformed

    private void itemRepresentanteRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRepresentanteRegistrarActionPerformed
        VentanaGRepresentante v = new VentanaGRepresentante(this, true);
        v.setLocationRelativeTo(null);
        v.setVisible(true);                   
    }//GEN-LAST:event_itemRepresentanteRegistrarActionPerformed

    private void itemSucursalRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSucursalRegistrarActionPerformed
        VentanaGSucursal v = new VentanaGSucursal(this, true);
        v.setLocationRelativeTo(null);
        v.setVisible(true);         
    }//GEN-LAST:event_itemSucursalRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(new NoireLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ReportesClientesPersona;
    private javax.swing.JMenu ReportesEmpleados;
    private javax.swing.JMenuItem itemCrearCuentaA;
    private javax.swing.JMenuItem itemCuentaARegistrar;
    private javax.swing.JMenuItem itemEliminarBanco;
    private javax.swing.JMenuItem itemEliminarC_PR;
    private javax.swing.JMenuItem itemEliminarC_org;
    private javax.swing.JMenuItem itemEliminarCuentaA;
    private javax.swing.JMenuItem itemEmpleadoRegistrar;
    private javax.swing.JMenuItem itemIniciarSesiónBanco;
    private javax.swing.JMenuItem itemIniciarSesiónC_Org;
    private javax.swing.JMenuItem itemIniciarSesiónC_PR;
    private javax.swing.JMenuItem itemListarC_Org;
    private javax.swing.JMenuItem itemListarC_PR;
    private javax.swing.JMenuItem itemListarCuentaA;
    private javax.swing.JMenuItem itemModificarBanco;
    private javax.swing.JMenuItem itemModificarC_Org;
    private javax.swing.JMenuItem itemModificarC_PR;
    private javax.swing.JMenuItem itemModificarCuenteA;
    private javax.swing.JMenuItem itemRAlfabeticoC_PR;
    private javax.swing.JMenuItem itemRGeneroC_PR;
    private javax.swing.JMenuItem itemRegistrarBanco;
    private javax.swing.JMenuItem itemRegistrarC_Org;
    private javax.swing.JMenuItem itemRegistrarC_PR;
    private javax.swing.JMenuItem itemRepresentanteRegistrar;
    private javax.swing.JMenuItem itemSucursalRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuBanco;
    private javax.swing.JMenu menuC_Organizacion;
    private javax.swing.JMenu menuC_PersonasReales;
    private javax.swing.JMenu menuCuentaAhorro;
    private javax.swing.JMenu menuCuentaCorriente;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenu menuRepresentante;
    private javax.swing.JMenu menuSucursal;
    private javax.swing.JMenu reportesCuentaAhorro;
    private javax.swing.JMenu reportesCuentaCorriente;
    private javax.swing.JMenu reportesSucursal;
    // End of variables declaration//GEN-END:variables
}
