/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.unicolombo.ingsistemas.poo.finanzas.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author carlos david
 */
public class VentanaGRepresentante extends javax.swing.JDialog {

    /**
     * Creates new form VentanaGRepresentante
     */
    public VentanaGRepresentante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaImagen = new javax.swing.JLabel();
        tituloFormulario = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        Jlabel = new javax.swing.JLabel();
        campoIdCAhorro = new javax.swing.JTextField();
        campoIdCAhorro1 = new javax.swing.JTextField();
        Jlabel1 = new javax.swing.JLabel();
        campoIdCAhorro2 = new javax.swing.JTextField();
        Jlabel2 = new javax.swing.JLabel();
        campoIdCAhorro3 = new javax.swing.JTextField();
        Jlabel3 = new javax.swing.JLabel();
        campoIdCAhorro4 = new javax.swing.JTextField();
        Jlabel4 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonBusacar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de gestion de representantes");

        etiquetaImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/userCliente 126px.png"))); // NOI18N
        etiquetaImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(0, 0, 204));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Formulario de gestion de representantes");

        panelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true), "Datos del Representante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        Jlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel.setText("Telefono");

        campoIdCAhorro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoIdCAhorro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoIdCAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdCAhorroActionPerformed(evt);
            }
        });

        campoIdCAhorro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoIdCAhorro1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoIdCAhorro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdCAhorro1ActionPerformed(evt);
            }
        });

        Jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel1.setText("Nombre");

        campoIdCAhorro2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoIdCAhorro2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoIdCAhorro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdCAhorro2ActionPerformed(evt);
            }
        });

        Jlabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel2.setText("Genero");

        campoIdCAhorro3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoIdCAhorro3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoIdCAhorro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdCAhorro3ActionPerformed(evt);
            }
        });

        Jlabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel3.setText("Email");

        campoIdCAhorro4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoIdCAhorro4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoIdCAhorro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdCAhorro4ActionPerformed(evt);
            }
        });

        Jlabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel4.setText("ID");

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoIdCAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(Jlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoIdCAhorro1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(Jlabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoIdCAhorro2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(Jlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoIdCAhorro3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(Jlabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoIdCAhorro4, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel1)
                    .addComponent(campoIdCAhorro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel)
                    .addComponent(campoIdCAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel2)
                    .addComponent(campoIdCAhorro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel3)
                    .addComponent(campoIdCAhorro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel4)
                    .addComponent(campoIdCAhorro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200))
        );

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add 48px.png"))); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonBusacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/search 48px.png"))); // NOI18N

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/edid 48px.png"))); // NOI18N

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete 48px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(botonBusacar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tituloFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBusacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdCAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdCAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdCAhorroActionPerformed

    private void campoIdCAhorro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdCAhorro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdCAhorro1ActionPerformed

    private void campoIdCAhorro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdCAhorro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdCAhorro2ActionPerformed

    private void campoIdCAhorro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdCAhorro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdCAhorro3ActionPerformed

    private void campoIdCAhorro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdCAhorro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdCAhorro4ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"Registro realizado con exito");
    }//GEN-LAST:event_botonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGRepresentante dialog = new VentanaGRepresentante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel;
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JLabel Jlabel2;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel Jlabel4;
    private javax.swing.JButton botonBusacar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoIdCAhorro;
    private javax.swing.JTextField campoIdCAhorro1;
    private javax.swing.JTextField campoIdCAhorro2;
    private javax.swing.JTextField campoIdCAhorro3;
    private javax.swing.JTextField campoIdCAhorro4;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
