/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.unicolombo.ingsistemas.poo.finanzas.gui;

import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.BancoJpaController;
import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.exceptions.IllegalOrphanException;
import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.exceptions.NonexistentEntityException;
import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.exceptions.PreexistingEntityException;
import co.edu.unicolombo.ingsistemas.poo.finanzas.entity.Banco;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author jimmy
 */
public class VentanaGBanco extends javax.swing.JDialog {

    /**
     * Creates new form VentanaUsuario
     */
    public VentanaGBanco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaImagen = new javax.swing.JLabel();
        tituloFormulario = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        Jlabel = new javax.swing.JLabel();
        JLabel = new javax.swing.JLabel();
        Jlabel3 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoDireccion = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JPasswordField();
        campoConfirmarContraseña = new javax.swing.JPasswordField();
        Jlabel1 = new javax.swing.JLabel();
        campoNit = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonBusacar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario para gestionar Bancos");

        etiquetaImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/bankLogo-icon.png"))); // NOI18N
        etiquetaImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(0, 0, 204));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Formulario de gestion del banco");

        panelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true), "Datos del Banco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        Jlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel.setText("Email:");

        JLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel.setText("Telefono:");

        Jlabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel3.setText("Direccion:");

        JLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel4.setText("Contraseña:");

        JLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel5.setText("Confirmar contraseña:");

        campoEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoContraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoConfirmarContraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        Jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel1.setText("NIT:");

        campoNit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoNit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNitActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nombre.setText("Nombre:");

        campoNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormularioLayout.createSequentialGroup()
                                .addComponent(JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(campoTelefono)
                            .addComponent(campoConfirmarContraseña)
                            .addComponent(campoDireccion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(campoEmail))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel1)
                    .addComponent(campoNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlabel)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel3)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel4)
                    .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel5)
                    .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add 48px.png"))); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonBusacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/search 48px.png"))); // NOI18N
        botonBusacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusacarActionPerformed(evt);
            }
        });

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/edid 48px.png"))); // NOI18N
        botonEditar.setEnabled(false);
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete 48px.png"))); // NOI18N
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(botonBusacar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelFormulario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tituloFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBusacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarCampos() {
        campoNit.setText("");
        campoNombre.setText("");
        campoEmail.setText("");
        campoTelefono.setText("");
        campoDireccion.setText("");
        campoContraseña.setText("");
        campoConfirmarContraseña.setText("");
        return;
    }
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        int vali = JOptionPane.showConfirmDialog(this, "¿Esta seguro(a) que desea guardar?", "Confirme", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (vali == JOptionPane.YES_OPTION) {
            String nit = campoNit.getText();
            String Nombre = campoNombre.getText();
            String email = campoEmail.getText();
            String telefono = campoTelefono.getText();
            String direccion = campoDireccion.getText();
            String contraseña = String.valueOf(campoContraseña.getPassword());
            String confirmarContraseña = String.valueOf(campoConfirmarContraseña.getPassword());
            Banco b = new Banco();
            b.setNit(nit);
            b.setNombre(Nombre);
            b.setEmail(email);
            b.setTelefono(telefono);
            b.setDireccion(direccion);
            b.setClave(contraseña);
            EntityManagerFactory conexionBd = Persistence.createEntityManagerFactory("Pro_Aula-Finanzas_POOPU");
            BancoJpaController crudl = new BancoJpaController(conexionBd);
            try {
                crudl.create(b);
                int total = crudl.getBancoCount();
                String mensaje = "Banco guardado con exito!!.\n Total: " + total;
                JOptionPane.showMessageDialog(this, mensaje);
                limpiarCampos();
            } catch (PreexistingEntityException ex) {
                JOptionPane.showMessageDialog(this, "Existe un Banco con este nit: " + nit);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el Banco. ");
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void campoNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNitActionPerformed
    public EntityManagerFactory conectar() {
        EntityManagerFactory conexion_bd = Persistence.createEntityManagerFactory("Pro_Aula-Finanzas_POOPU");
        return conexion_bd;
    }
    Banco b;
    private void botonBusacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusacarActionPerformed
        String nit = campoNit.getText();
        if (nit == null || nit.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nit del banco es necesario. ");
            return;
        }
        EntityManagerFactory conexionBd = conectar();
        BancoJpaController crudlBanco = new BancoJpaController(conexionBd);

        b = crudlBanco.findBanco(nit);
        if (b == null) {
            JOptionPane.showMessageDialog(this, "El banco con NIT" + nit + ", no existe.");
        }
        campoNombre.setText(b.getNombre());
        campoDireccion.setText(b.getDireccion());
        campoEmail.setText(b.getEmail());
        campoTelefono.setText(b.getTelefono());
        botonEditar.setEnabled(true);
        botonEliminar.setEnabled(true);
    }//GEN-LAST:event_botonBusacarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        int vali = JOptionPane.showConfirmDialog(this, "¿Esta seguro(a) que desea editar?", "Confirme", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (vali == JOptionPane.YES_OPTION) {
            String telefono = campoTelefono.getText();
            String direccion = campoDireccion.getText();
            String email = campoEmail.getText();
            String contraseña = String.valueOf(campoContraseña.getPassword());

            b.setTelefono(telefono);
            b.setDireccion(direccion);
            b.setEmail(email);
            b.setClave(contraseña);
            EntityManagerFactory conexionBD = conectar();
            BancoJpaController crudBanco = new BancoJpaController(conexionBD);
            try {
                crudBanco.edit(b);
                JOptionPane.showMessageDialog(this, "Editado con exito!!");
                limpiarCampos();
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "El banco no existe");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al editar banco");
            }
        }


    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int vali = JOptionPane.showConfirmDialog(this, "¿Seguro(s) que desea "
                + "eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (vali == JOptionPane.YES_OPTION) {
            EntityManagerFactory conexionBD = conectar();
            BancoJpaController crudBanco = new BancoJpaController(conexionBD);
            try {
                crudBanco.destroy(b.getNit());
                limpiarCampos();
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "El banco no existe");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al eliminar banco");
            }
        }

    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGBanco dialog = new VentanaGBanco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton botonBusacar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JPasswordField campoConfirmarContraseña;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNit;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
