/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.unicolombo.ingsistemas.poo.finanzas.gui;

import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.BancoJpaController;
import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.ClienteJpaController;
import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.ClientePersonaJpaController;
import co.edu.unicolombo.ingsistemas.poo.finanzas.crudl.exceptions.PreexistingEntityException;
import co.edu.unicolombo.ingsistemas.poo.finanzas.entity.Banco;
import co.edu.unicolombo.ingsistemas.poo.finanzas.entity.Cliente;
import co.edu.unicolombo.ingsistemas.poo.finanzas.entity.ClientePersona;
import static java.lang.String.format;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jimmy
 */
public class VentanaGC_PR extends javax.swing.JDialog {

    /**
     * Creates new form VentanaUsuario
     */
    public VentanaGC_PR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        campoFNacimientoP.setText("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaImagen = new javax.swing.JLabel();
        tituloFormulario = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        Jlabel = new javax.swing.JLabel();
        JLabel = new javax.swing.JLabel();
        Jlabel3 = new javax.swing.JLabel();
        JLabel4 = new javax.swing.JLabel();
        Jlabel4 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        Jlabel7 = new javax.swing.JLabel();
        Jlabel8 = new javax.swing.JLabel();
        Jlabel9 = new javax.swing.JLabel();
        campoNombreP = new javax.swing.JTextField();
        campoDireccionP = new javax.swing.JTextField();
        campoDniP = new javax.swing.JTextField();
        campoContraseñaP = new javax.swing.JPasswordField();
        campoConfirmarContraseñaP = new javax.swing.JPasswordField();
        campoEmailP = new javax.swing.JTextField();
        CampoApellidoP = new javax.swing.JTextField();
        campoFNacimientoP = new javax.swing.JTextField();
        campoGeneroP = new javax.swing.JTextField();
        comboBancos = new javax.swing.JComboBox<>();
        Jlabel11 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonBusacar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario para gestionar Clientes de tipo Persona");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        etiquetaImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/userCliente 126px.png"))); // NOI18N
        etiquetaImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(0, 0, 204));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Formulario de gestion de clientes de tipo personas");

        panelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true), "Datos de la persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        Jlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel.setText("Nombre:");

        JLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel.setText("Dirección:");

        Jlabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel3.setText("DNI:");

        JLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel4.setText("Contraseña:");

        Jlabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel4.setText("Email:");

        JLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel5.setText("Confirmar contraseña:");

        Jlabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel7.setText("Apellido:");

        Jlabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel8.setText("Fecha de Nacimiento:");

        Jlabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel9.setText("Genero:");

        campoNombreP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoNombreP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombrePActionPerformed(evt);
            }
        });

        campoDireccionP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoDireccionP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoDniP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoDniP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoContraseñaP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoContraseñaP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoConfirmarContraseñaP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoConfirmarContraseñaP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoEmailP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoEmailP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        CampoApellidoP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CampoApellidoP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        campoFNacimientoP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoFNacimientoP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoFNacimientoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoFNacimientoPFocusLost(evt);
            }
        });
        campoFNacimientoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoFNacimientoPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoFNacimientoPMouseExited(evt);
            }
        });

        campoGeneroP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoGeneroP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoGeneroP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoGeneroPFocusLost(evt);
            }
        });
        campoGeneroP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoGeneroPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoGeneroPMouseExited(evt);
            }
        });

        comboBancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar un..." }));

        Jlabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jlabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel11.setText("Banco");

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jlabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jlabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(Jlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jlabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDniP)
                            .addComponent(campoFNacimientoP)
                            .addComponent(CampoApellidoP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoGeneroP, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabel5)
                            .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addComponent(JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoContraseñaP)
                            .addComponent(campoEmailP)
                            .addComponent(campoDireccionP)
                            .addComponent(campoNombreP)
                            .addComponent(campoConfirmarContraseñaP)
                            .addComponent(comboBancos, 0, 267, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel)
                    .addComponent(campoNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(campoDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel4)
                    .addComponent(campoEmailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel4)
                    .addComponent(campoContraseñaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel5)
                    .addComponent(campoConfirmarContraseñaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlabel11))
                .addGap(9, 9, 9)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel7)
                    .addComponent(CampoApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel8)
                    .addComponent(campoFNacimientoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel9)
                    .addComponent(campoGeneroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel3)
                    .addComponent(campoDniP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/add 48px.png"))); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonBusacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/search 48px.png"))); // NOI18N
        botonBusacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusacarActionPerformed(evt);
            }
        });

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/edid 48px.png"))); // NOI18N

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/ingsistemas/poo/finanzas/icon/delete 48px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(botonBusacar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tituloFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBusacar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombrePActionPerformed


    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        int posBanco = comboBancos.getSelectedIndex();
        if(posBanco == 0){
            JOptionPane.showMessageDialog(this, "Debe escojer un banco");
            return;

        }
        String textoFecha = campoFNacimientoP.getText();
        String fechaPartes[] = textoFecha.split("-");
        int año = 0, mes = 0, dia = 0;
        String añoS = null;
        String mesS = null;
        String diaS = null;
        if (fechaPartes.length < 3 || fechaPartes.length < 3) {
            JOptionPane.showMessageDialog(this, "La fecha debe estar en formato (año-mes-dia).");

        } else {
            añoS = fechaPartes[0];
            mesS = fechaPartes[1];
            diaS = fechaPartes[2];
            try {
                año = Integer.parseInt(añoS);
                mes = Integer.parseInt(mesS);
                dia = Integer.parseInt(diaS);
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(this, "El formato debe ser: (yyyy-MM-dd), como se le especifica en el formulario.");
                return;
            }

            if (año < 0 || añoS.length() > 4 || añoS.length() < 4) {
                JOptionPane.showMessageDialog(this, "El formato debe ser: (año-mes-dia), verifique el año.");
                return;
            }
            if (mes < 0 || mes > 12 || mesS.length() > 2 || mesS.length() < 2) {
                JOptionPane.showMessageDialog(this, "El formato debe ser: (año-mes-dia), verifique el mes.");
                return;
            }
            if (dia < 0 || dia > 31 || diaS.length() > 2 || mesS.length() < 2) {
                JOptionPane.showMessageDialog(this, "El formato debe ser: (año-mes-dia), verifique el dia.");
                return;
            }

//                
        }

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = null;
        try {
            fecha = format.parse(añoS + "-" + mesS + "-" + diaS);
        } catch (ParseException ex) {
            Logger.getLogger(VentanaGC_PR.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date nacimiento = fecha;
        String nombre = campoNombreP.getText();
        String direccion = campoDireccionP.getText();
        String email = campoEmailP.getText();
        String dni = campoDniP.getText();
        String apellido = CampoApellidoP.getText();

        String genero = campoGeneroP.getText();
        String contraseña = String.valueOf(campoContraseñaP.getPassword());
        String confirmarContraseña = String.valueOf(campoConfirmarContraseñaP.getPassword());
        //ClientePersona cp = new ClientePersona();
        ClientePersona cp = new ClientePersona();
        cp.setNombre(nombre);
        cp.setDireccion(direccion);
        cp.setEmail(email);
        cp.setClave(contraseña);
        // datos del cliente
        //ClientePersona cp = (ClientePersona)c;
        cp.setDni(dni);
        cp.setApellido(apellido);
        cp.setFNacimiento(nacimiento);
        cp.setGenero(genero);

        EntityManagerFactory conexionBd = Persistence.createEntityManagerFactory("Pro_Aula-Finanzas_POOPU");
        ClienteJpaController crudlC = new ClienteJpaController(conexionBd);
        ClientePersonaJpaController crudl = new ClientePersonaJpaController(conexionBd);
        try {
            Banco b = bancos.get(posBanco-1);
            b.getNit();
            cp.setBancosId(b);
            crudlC.create(cp);
            cp.setClienteId(cp);
            crudl.create(cp);
            JOptionPane.showMessageDialog(this, "Cliente guardado con exito.");
        } catch (PreexistingEntityException ex) {
            JOptionPane.showMessageDialog(this, "El dni" + dni + ", ya existe");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos.");
        }


    }//GEN-LAST:event_botonGuardarActionPerformed

    List<Banco> bancos;

    public void cargarBancos() {
        EntityManagerFactory con = conectar();
        BancoJpaController crudBanco = new BancoJpaController(con);
        bancos = crudBanco.findBancoEntities();
        if (bancos == null || bancos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar los bancos");
            botonGuardar.setEnabled(false);
            return;
        }
        for (Banco banco : bancos) {
            comboBancos.addItem(banco.getNombre());
        }

    }
    private void botonBusacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusacarActionPerformed
        String dni = campoDniP.getText();
        if (dni == null || dni.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El dni es necesario para consultar sus datos.");
        }
        EntityManagerFactory conexionBd = conectar();
        ClientePersonaJpaController crudlCP = new ClientePersonaJpaController(conexionBd);

        ClientePersona cp = crudlCP.findClientePersona(dni);
        if (cp == null) {
            JOptionPane.showMessageDialog(this, "El dni" + dni + ", no existe!!.");
        }
        CampoApellidoP.setText(cp.getApellido());
        campoFNacimientoP.setText(cp.getFNacimiento().toString());
        campoGeneroP.setText(cp.getGenero());

    }//GEN-LAST:event_botonBusacarActionPerformed

    private void campoFNacimientoPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoFNacimientoPMouseExited
        String formato = campoFNacimientoP.getText();
        if (formato == null || formato.isBlank()) {
            campoFNacimientoP.setText("yyyy-MM-dd");
        }
    }//GEN-LAST:event_campoFNacimientoPMouseExited

    private void campoFNacimientoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoFNacimientoPMouseClicked
        String formato = campoFNacimientoP.getText();
        if (formato != null && formato.equalsIgnoreCase("yyyy-MM-dd")) {
            campoFNacimientoP.setText("");
        }

    }//GEN-LAST:event_campoFNacimientoPMouseClicked

    private void campoFNacimientoPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFNacimientoPFocusLost
        campoFNacimientoPMouseExited(null);
    }//GEN-LAST:event_campoFNacimientoPFocusLost

    private void campoGeneroPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoGeneroPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGeneroPFocusLost

    private void campoGeneroPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoGeneroPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGeneroPMouseClicked

    private void campoGeneroPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoGeneroPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGeneroPMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cargarBancos();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGC_PR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGC_PR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGC_PR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGC_PR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGC_PR dialog = new VentanaGC_PR(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoApellidoP;
    private javax.swing.JLabel JLabel;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JLabel Jlabel11;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel Jlabel4;
    private javax.swing.JLabel Jlabel7;
    private javax.swing.JLabel Jlabel8;
    private javax.swing.JLabel Jlabel9;
    private javax.swing.JButton botonBusacar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JPasswordField campoConfirmarContraseñaP;
    private javax.swing.JPasswordField campoContraseñaP;
    private javax.swing.JTextField campoDireccionP;
    private javax.swing.JTextField campoDniP;
    private javax.swing.JTextField campoEmailP;
    private javax.swing.JTextField campoFNacimientoP;
    private javax.swing.JTextField campoGeneroP;
    private javax.swing.JTextField campoNombreP;
    private javax.swing.JComboBox<String> comboBancos;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables

    public EntityManagerFactory conectar() {
        EntityManagerFactory conexionBd = Persistence.createEntityManagerFactory("Pro_Aula-Finanzas_POOPU");
        return conexionBd;
    }
}
